#!/bin/bash
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-0.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-1.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-2.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-3.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-4.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-5.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-6.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-7.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-8.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-9.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-10.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-11.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-12.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-13.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-14.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-15.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-16.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-17.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-18.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-19.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-20.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-21.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-22.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-23.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-24.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-25.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-26.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-27.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-28.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-29.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-30.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-31.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-32.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-33.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-34.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-35.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-36.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-37.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-38.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-39.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-40.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-41.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-42.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-43.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-44.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-45.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-46.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-47.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-48.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-49.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-50.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-51.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-52.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-53.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-54.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-55.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-56.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-57.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-58.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-59.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-60.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-61.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-62.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-63.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-64.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-65.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-66.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-67.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-68.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-69.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-70.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-71.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-72.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-73.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-74.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-75.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-76.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-77.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-78.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-79.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-80.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-81.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-82.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-83.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-84.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-85.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-86.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-87.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-88.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-89.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-90.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-91.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-92.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-93.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-94.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-95.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-96.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=gray" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-97.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=blur" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-98.png" http://localhost:8080/images && sleep 0.1
curl -H 'Expect:' -F "ACTION=edge" -F "IMAGE=@/home/twcam/pls/lab-rabbitmq-opencv/images-99.png" http://localhost:8080/images && sleep 0.1
